### ISSUE TITLE
What do you think about Node.js?

### ISSUE THREAD

**Issue by unixzii** [yorkie/ama#1]
I saw this repo in [your Zhihu answer](http://www.zhihu.com/question/32066000#answer-17195366) and I wanna bring some buzzling to you.  :)

Well,you know what,I'm going to create a blog completely on my own.That means I have to write both frontend web pages and backend server.I plan to use **Node.js** as backend and use **MongoDB** as database.Because I haven't touched the backend development before,I wonder whether you can give me some advice?

**Comment by yorkie** [comment]
I have no idea about that, because my private blog is just a static page. As for the comment system, I think there are some other tools that you can integrate into your post page.

So my advice:
1. using the static pages as the type of your website
2. using the comments integration like DUOSHUO.com to support comments

There are so many CLI tools to make 1st to do in simply way, here I suggest the hexo. Hope this could help you :)
